#!/usr/bin/env python3
"""Generate Supabase migration SQL for raw census CSV schemas."""

from __future__ import annotations

import csv
import glob
import os
import re
from collections import defaultdict
from pathlib import Path


ROOT = Path("/Users/anandagarwal/dsm_project")
RAW_DATA_DIR = ROOT / "raw_data"
MIGRATIONS_DIR = ROOT / "supabase" / "migrations"
MIGRATION_FILE = MIGRATIONS_DIR / "20260426165000_create_raw_census_tables.sql"


def table_group_name(csv_path: Path) -> str:
    name = csv_path.stem.replace("_states", "")
    name = name.replace("(", "").replace(")", "")
    name = name.replace("-", "_")
    name = re.sub(r"__+", "_", name)
    return f"raw_{name.lower()}"


def sanitize_col_name(raw: str) -> str:
    value = raw.replace("\ufeff", "").strip().lower()
    value = (
        value.replace("|", " ")
        .replace("/", " ")
        .replace(".", " ")
        .replace("-", " ")
        .replace("(", " ")
        .replace(")", " ")
        .replace("&", " and ")
    )
    value = re.sub(r"[^a-z0-9]+", "_", value)
    value = re.sub(r"_+", "_", value).strip("_")
    if not value:
        value = "col"
    if value[0].isdigit():
        value = f"col_{value}"
    return value


def read_header(csv_path: Path) -> list[str]:
    with csv_path.open("r", newline="", encoding="utf-8") as fh:
        return next(csv.reader(fh))


def generate_sql() -> str:
    csv_paths = sorted(Path(p) for p in glob.glob(str(RAW_DATA_DIR / "*" / "*.csv")))
    grouped: dict[str, list[Path]] = defaultdict(list)
    for path in csv_paths:
        grouped[table_group_name(path)].append(path)

    lines: list[str] = [
        "-- Auto-generated by scripts/generate_raw_census_migration.py",
        "create schema if not exists public;",
        "",
    ]

    for table_name in sorted(grouped.keys()):
        ordered_headers: list[str] = []
        for csv_path in sorted(grouped[table_name]):
            for col in read_header(csv_path):
                if col not in ordered_headers:
                    ordered_headers.append(col)

        used_names: set[str] = set()
        column_names: list[str] = []
        for raw_col in ordered_headers:
            base = sanitize_col_name(raw_col)
            name = base
            counter = 2
            while name in used_names:
                name = f"{base}_{counter}"
                counter += 1
            used_names.add(name)
            column_names.append(name)

        lines.append(f"create table if not exists public.{table_name} (")
        lines.append("  id bigserial primary key,")
        lines.append("  year integer not null check (year in (2001, 2011)),")
        for idx, column in enumerate(column_names):
            suffix = "," if idx < len(column_names) - 1 else ""
            lines.append(f"  {column} text{suffix}")
        lines.append(");")
        lines.append(
            f"create index if not exists {table_name}_year_idx on public.{table_name}(year);"
        )
        lines.append("")

    return "\n".join(lines) + "\n"


def main() -> None:
    MIGRATIONS_DIR.mkdir(parents=True, exist_ok=True)
    sql = generate_sql()
    MIGRATION_FILE.write_text(sql, encoding="utf-8")
    print(f"Wrote migration: {MIGRATION_FILE}")


if __name__ == "__main__":
    main()
