#!/usr/bin/env python3
"""Generate Supabase data-seeding migration for raw census CSV files."""

from __future__ import annotations

import csv
import glob
import re
from collections import defaultdict
from pathlib import Path


ROOT = Path("/Users/anandagarwal/dsm_project")
RAW_DATA_DIR = ROOT / "raw_data"
MIGRATIONS_DIR = ROOT / "supabase" / "migrations"
MIGRATION_FILE = MIGRATIONS_DIR / "20260426170000_seed_raw_census_data.sql"


def table_group_name(csv_path: Path) -> str:
    name = csv_path.stem.replace("_states", "")
    name = name.replace("(", "").replace(")", "")
    name = name.replace("-", "_")
    name = re.sub(r"__+", "_", name)
    return f"raw_{name.lower()}"


def sanitize_col_name(raw: str) -> str:
    value = raw.replace("\ufeff", "").strip().lower()
    value = (
        value.replace("|", " ")
        .replace("/", " ")
        .replace(".", " ")
        .replace("-", " ")
        .replace("(", " ")
        .replace(")", " ")
        .replace("&", " and ")
    )
    value = re.sub(r"[^a-z0-9]+", "_", value)
    value = re.sub(r"_+", "_", value).strip("_")
    if not value:
        value = "col"
    if value[0].isdigit():
        value = f"col_{value}"
    return value


def sql_literal(value: str | None) -> str:
    if value is None:
        return "NULL"
    text = value.strip()
    if text == "":
        return "NULL"
    return "'" + text.replace("'", "''") + "'"


def read_rows(csv_path: Path) -> tuple[list[str], list[list[str]]]:
    with csv_path.open("r", newline="", encoding="utf-8") as fh:
        reader = csv.reader(fh)
        header = next(reader)
        rows = [row for row in reader]
    return header, rows


def main() -> None:
    MIGRATIONS_DIR.mkdir(parents=True, exist_ok=True)

    csv_paths = sorted(Path(p) for p in glob.glob(str(RAW_DATA_DIR / "*" / "*.csv")))
    grouped: dict[str, list[Path]] = defaultdict(list)
    for path in csv_paths:
        grouped[table_group_name(path)].append(path)

    lines: list[str] = [
        "-- Auto-generated by scripts/generate_raw_census_seed_migration.py",
        "begin;",
        "",
    ]

    for table_name in sorted(grouped.keys()):
        # Build canonical raw-header order exactly as migration-generation logic.
        ordered_headers: list[str] = []
        for csv_path in sorted(grouped[table_name]):
            header, _ = read_rows(csv_path)
            for col in header:
                if col not in ordered_headers:
                    ordered_headers.append(col)

        # Build canonical SQL column names (same uniqueness logic as schema migration).
        used_names: set[str] = set()
        canonical_names: list[str] = []
        for raw_col in ordered_headers:
            base = sanitize_col_name(raw_col)
            name = base
            counter = 2
            while name in used_names:
                name = f"{base}_{counter}"
                counter += 1
            used_names.add(name)
            canonical_names.append(name)

        lines.append(f"truncate table public.{table_name} restart identity;")
        insert_cols = ["year"] + canonical_names
        lines.append(
            f"insert into public.{table_name} ({', '.join(insert_cols)}) values"
        )

        value_rows_sql: list[str] = []
        for csv_path in sorted(grouped[table_name]):
            year = int(csv_path.parent.name)
            header, rows = read_rows(csv_path)
            header_to_idx = {col: idx for idx, col in enumerate(header)}

            for row in rows:
                row_values = [str(year)]
                for canonical_raw_col in ordered_headers:
                    idx = header_to_idx.get(canonical_raw_col)
                    cell = row[idx] if idx is not None and idx < len(row) else None
                    row_values.append(sql_literal(cell))
                value_rows_sql.append(f"({', '.join(row_values)})")

        # Write in chunks to avoid overly large single INSERT.
        chunk_size = 500
        if value_rows_sql:
            first_chunk = True
            for start in range(0, len(value_rows_sql), chunk_size):
                chunk = value_rows_sql[start : start + chunk_size]
                if first_chunk:
                    lines.append(",\n".join(chunk) + ";")
                    first_chunk = False
                else:
                    lines.append(
                        f"insert into public.{table_name} ({', '.join(insert_cols)}) values"
                    )
                    lines.append(",\n".join(chunk) + ";")
        else:
            lines[-1] += " (2001" + "".join(", NULL" for _ in canonical_names) + ");"
            lines.append(f"delete from public.{table_name};")

        lines.append("")

    lines.append("commit;")
    lines.append("")

    MIGRATION_FILE.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote seed migration: {MIGRATION_FILE}")


if __name__ == "__main__":
    main()
